# Настройки плагина TownSystem

# Основные настройки
settings:
  # Название предмета Ратуши (используется в выдаче и меню)
  building-item-name: "&6Ратуша"

  # Радиус защиты вокруг зданий (в блоках)
  protection-radius: 10

  # Можно ли разрушать здания других команд
  allow-destroy-other-teams: true

# Настройки команд
teams:
  red:
    display_name: "&cКрасная команда"
    color: RED
  blue:
    display_name: "&9Синяя команда"
    color: BLUE
  green:
    display_name: "&aЗеленая команда"
    color: GREEN

# Настройки уровней зданий
building-levels:
  townhall:
    0:
      # Ресурсы для перехода на 1 уровень
      required-resources:
        STONE: 64
        OAK_LOG: 32
        IRON_INGOT: 16
      # Награда за улучшение
      reward:
        - "minecraft:emerald 5"
        - "townsystem:mine_block 1"
    1:
      required-resources:
        COBBLESTONE: 128
        IRON_INGOT: 32
        GOLD_INGOT: 8
      reward:
        - "minecraft:emerald 10"
        - "townsystem:magic_tower_block 1"

# Настройки других зданий (шаблон)
buildings:
  mine:
    display-name: "&7Шахта"
    item-material: "IRON_PICKAXE"
  farm:
    display-name: "&aФерма"
    item-material: "GOLDEN_HOE"
  magic_tower:
    display-name: "&5Башня чародея"
    item-material: "ENCHANTING_TABLE"

# Сообщения
messages:
  no-permission: "&cУ вас нет прав на эту команду!"
  not-in-team: "&cВы должны состоять в команде!"
  building-placed: "&aВы установили здание для команды %team%"
  building-destroyed: "&aВы разрушили здание команды %team%"
  chest-protected: "&cЭтот сундук защищен командой %team%!"
  level-up: "&aЗдание улучшено до уровня %level%!"
  resources-needed: "&eТребуется для улучшения:"