# Настройки плагина TownSystem

# Основные настройки
settings:
  # Название предмета Ратуши (используется в выдаче и меню)
  building-item-name: "&6Ратуша"

  # Радиус защиты вокруг зданий (в блоках)
  protection-radius: 10

  # Можно ли разрушать здания других команд
  allow-destroy-other-teams: true

# Настройки команд
teams:
  red:
    display_name: "&cКрасная команда"
    color: RED
  blue:
    display_name: "&9Синяя команда"
    color: BLUE
  green:
    display_name: "&aЗеленая команда"
    color: GREEN

# Настройки уровней зданий
buildings:
  townhall:
    display-name: "&6Ратуша"
    levels:
      0:
        display-name: "&7Деревянная ратуша"
        resources:
          STONE: 64
          OAK_LOG: 32
          IRON_INGOT: 16
        rewards:
          EMERALD: 5
          IRON_PICKAXE: 1
      1:
        display-name: "&fКаменная ратуша"
        resources:
          COBBLESTONE: 128
          IRON_INGOT: 32
          GOLD_INGOT: 8
        rewards:
          EMERALD: 10
          DIAMOND: 2

material-names:
  STONE: "Камень"
  OAK_LOG: "Дубовые бревна"
  IRON_INGOT: "Железные слитки"
  EMERALD: "Изумруд"
  IRON_PICKAXE: "Железная кирка"
  COBBLESTONE: "Булыжник"
  GOLD_INGOT: "Золотой слиток"
  DIAMOND: "Алмаз"
# Сообщения
messages:
  no-permission: "&cУ вас нет прав на эту команду!"
  not-in-team: "&cВы должны состоять в команде!"
  building-placed: "&aВы установили здание для команды %team%"
  building-destroyed: "&aВы разрушили здание команды %team%"
  chest-protected: "&cЭтот сундук защищен командой %team%!"
  level-up: "&aЗдание улучшено до уровня %level%!"
  resources-needed: "&eТребуется для улучшения:"