# Настройки плагина TownSystem

# Основные настройки
settings:
  # Название предмета Ратуши (используется в выдаче и меню)
  building-item-name: "&6Ратуша"

  # Радиус защиты вокруг зданий (в блоках)
  protection-radius: 10

  # Можно ли разрушать здания других команд
  allow-destroy-other-teams: true

# Настройки команд
teams:
  red:
    display_name: "&cКрасная команда"
    color: RED
  blue:
    display_name: "&9Синяя команда"
    color: BLUE
  green:
    display_name: "&aЗеленая команда"
    color: GREEN

# Настройки уровней зданий
buildings:
  townhall:
    display-name: "&6Ратуша"
    material: END_STONE
    max-hp: 100
    hp-bar:
      visible: true
      title: "&cПрочность здания: {hp}/{max_hp}"
      color: RED
      style: SEGMENTED_20
    break-sound: ENTITY_IRON_GOLEM_DAMAGE
    destroy-sound: ENTITY_IRON_GOLEM_DEATH
    levels:
      1:
        display-name: "Деревянная ратуша"
        resources:
          STONE: 64
          OAK_LOG: 32
        rewards:
          - "mill:1"
          - "mine:1"
        chest-limit: 6
        radius: 5
      2:
        display-name: "Каменная ратуша"
        resources:
          IRON_INGOT: 16
          COBBLESTONE: 128
        rewards:
          - "smelter:1"
        chest-limit: 10
        radius: 5
      3:
        display-name: "Укрепленная ратуша"
        resources:
          GOLD_INGOT: 8
          IRON_BLOCK: 10
        rewards:
          - "wizard_tower:1"
        chest-limit: 14
        radius: 7
      4:
        display-name: "Роскошная ратуша"
        resources:
          DIAMOND: 4
          OBSIDIAN: 20
        rewards:
          - "hell_altar:1"
        chest-limit: 20
        radius: 10
      5:
        display-name: "Эпическая ратуша"
        resources:
          NETHERITE_INGOT: 2
          EMERALD_BLOCK: 8
        rewards: [ ]
        chest-limit: 28
        radius: 10


material-names:
  STONE: "Камень"
  OAK_LOG: "Дубовые бревна"
  IRON_INGOT: "Железные слитки"
  EMERALD: "Изумруд"
  IRON_PICKAXE: "Железная кирка"
  COBBLESTONE: "Булыжник"
  GOLD_INGOT: "Золотой слиток"
  DIAMOND: "Алмаз"
# Сообщения
messages:
  no-permission: "&cУ вас нет прав на эту команду!"
  not-in-team: "&cВы должны состоять в команде!"
  building-placed: "&aВы установили здание для команды %team%"
  building-destroyed: "&aВы разрушили здание команды %team%"
  chest-protected: "&cЭтот сундук защищен командой %team%!"
  level-up: "&aЗдание улучшено до уровня %level%!"
  resources-needed: "&eТребуется для улучшения:"