name: TownSystem
version: '1.0-SNAPSHOT'
main: org.showlee.townSystem.TownSystem
api-version: '1.21'
description: Плагин для системы улучшения городских построек через сбор ресурсов
author: ShowLee
commands:
  giveratusha:
    description: Выдать блок Ратуши
    usage: /giveratusha